apiVersion: apps/v1
kind: Deployment
metadata:
  name: rakkerman1
spec:
  selector:
    matchLabels:
      app: iot
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: iot
    spec:
      hostNetwork: true
      containers:
      - name: rakkerman1
        image: rakkerman1/raspberrypi
        ports:
           - containerPort: 9005
             hostPort: 9005
      
